networks:
  weather_app_network:
    external: true

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: weather_app
    command: python3 app/main.py
    depends_on:
      - redis
      - localstack
    networks:
      - weather_app_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: weather_app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - weather_app_network
    command: redis-server --appendonly yes

  localstack:
    image: localstack/localstack:latest
    restart: unless-stopped
    container_name: weather_app_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - weather_app_network

volumes:
  redis_data:
  localstack_data:
